version: ""
services:
  web:
    build: .
    # command: python backend/app.py
    # entrypoint: ["python", "backend/app.py"]
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./backend/app.py
    ports: ['5000:5000']
    # ports:
    #  - "5000:5000"
    expose:
      # Opens port 3306 on the container
      - '5000'
    depends_on:
    - "db"
    # environment:
    #  - FLASK_ENV=development # used by the web app to initialize the Flask App in Prod Mode


  db:
    image: mysql:5.7
    restart: always
    # command: --init-file backend/data/init.sql
    # volumes:
    #     - ./init.sql:/backend/data/init.sql
    environment:
      MYSQL_DATABASE: 'songsdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

# Names our volume
volumes:
  my-db: